[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"
[project]
name='RKkit'
version='0.1.4'
authors = [
  { name="Thierry Dumont", email="tdumont@math.cnrs.fr" },
] 
description="Playing with Runge-Kutta methods"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "GPL-3.0-or-later"
license-files = ["LICENSE"]
[project.optional-dependencies]
passagemath = ["passagemath-standard","passagemath-plot",
                                   "passagemath-symbolics",
                                   "passagemath-categories",
                                   "passagemath-combinat",
                                   "passagemath-flint",
                                   "passagemath-environment",
                                   "passagemath-singular",]
[project.urls]
Homepage = "https://github.com/Thierry-Dumont/RKkit"
Issues = "https://github.com/Thierry-Dumont/RKkit/issues"
 
