[build-system]
requires = ["setuptools>=65.0"]
build-backend = "setuptools.build_meta"
[tool.setuptools]
packages= ["RKkit","RKkit.rkkit","RKkit.methods"]
[project]
name = "RKkit"
version = "1.0.0"
description = "Build Runge-Kutta methods and compute their properties"
readme = "README.md"
authors = [
    {name = "Thierry Dumont", email = "thierry@thierry-dumont.fr"}
]
maintainers = [
    {name = "Thierry Dumont", email = "thierry@thierry-dumont.fr"}
]

keywords = [
    "Numerical Solufion of Differential Equations",
    "Runge-Kutta Methods",
    "Rooted Trees"
]
license = "MIT"
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Scientific :: Mathematics",
    "Topic :: Scientific/Engineering :: Numerical Analysis"
]
requires-python = ">=3.10"
dependencies = [
    "passagemath-plot",
    "passagemath-standard",
    "passagemath-flint",
    "passagemath-combinat"
]
[project.urls]
Homepage = "https://github.com/Thierry-Dumont/RKkit"
Repository = "https://github.com/Thierry-Dumont/RKkit"
Issues = "https://github.com/Thierry-Dumont/RKkit/issues"


[tool.setuptools.package-data]
RKkit  = [
    "rkkit/*",
    "methods/*"
    ]
[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test.py"]
python_classes = ["TestRKkit"]
python_functions = ["test*"]
addopts = "-v"



