[tox]
envlist = py313

[testenv:.pkg]
passenv =
    CPATH
    LIBRARY_PATH

[testenv]
usedevelop = True
extras = passagemath

setenv =
    # For access to _doctest_environment.py
    PYTHONPATH=.

allowlist_externals =
    bash

commands =
    python PythonExamples/AllProperties.py
    python PythonExamples/Example.py
    python PythonExamples/Gaussian.py
    # python PythonExamples/GoodAndBad.py
    python PythonExamples/RadauByCollocation.py
    python PythonExamples/Tchebychev.py
    bash -c 'yes | python PythonExamples/Test.py'
    sage -tp --force-lib --environment=_doctest_environment RKkit/
